name: Check Ovechkin Goals

on:
 schedule:
     - cron: "1/5 23-26 3 3 *"
     - cron: "1/5 0-3 6 3 *"
     - cron: "1/5 0-3 8 3 *"
     - cron: "1/5 19-22 9 3 *"
     - cron: "1/5 2-5 12 3 *"
     - cron: "1/5 2-5 14 3 *"
     - cron: "1/5 21-24 15 3 *"
     - cron: "1/5 23-26 18 3 *"
     - cron: "1/5 23-26 20 3 *"
     - cron: "1/5 21-24 22 3 *"
     - cron: "1/5 0-3 26 3 *"
     - cron: "1/5 23-26 27 3 *"
     - cron: "1/5 19-22 30 3 *"
     - cron: "1/5 23-26 1 4 *"
     - cron: "1/5 23-26 2 4 *"
     - cron: "1/5 23-26 4 4 *"
     - cron: "1/5 16-19 6 4 *"
     - cron: "1/5 23-26 10 4 *"
     - cron: "1/5 16-19 12 4 *"
     - cron: "1/5 22-25 13 4 *"
     - cron: "1/5 0-3 16 4 *"
     - cron: "1/5 23-26 17 4 *"

  workflow_dispatch: # Allows manual execution

jobs:
  check-goals:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Goal Checker Script
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_COMMIT_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: python check_for_goals.py

      - name: Commit State File
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add goal_state.json
          git commit -m "Update goal state" || echo "No changes to commit"
          git push
