name: Check Ovechkin Goals

on:
  schedule:
     - cron: '* 23 3 3 *'
     - cron: '* 0,1,2 4 3 *'
     - cron: '* 0,1,2,3 6 3 *'
     - cron: '* 0,1,2,3 8 3 *'
     - cron: '* 19,20,21,22 9 3 *'
     - cron: '* 2,3,4,5 12 3 *'
     - cron: '* 2,3,4,5 14 3 *'
     - cron: '* 21,22,23 15 3 *'
     - cron: '* 0 16 3 *'
     - cron: '* 23 18 3 *'
     - cron: '* 0,1,2 19 3 *'
     - cron: '* 23 20 3 *'
     - cron: '* 0,1,2 21 3 *'
     - cron: '* 21,22,23 22 3 *'
     - cron: '* 0 23 3 *'
     - cron: '* 0,1,2,3 26 3 *'
     - cron: '* 23 27 3 *'
     - cron: '* 0,1,2 28 3 *'
     - cron: '* 19,20,21,22 30 3 *'
     - cron: '* 23 1 4 *'
     - cron: '* 0,1,2 2 4 *'
     - cron: '* 23 2 4 *'
     - cron: '* 0,1,2 3 4 *'
     - cron: '* 23 4 4 *'
     - cron: '* 0,1,2 5 4 *'
     - cron: '* 16,17,18,19 6 4 *'
     - cron: '* 23 10 4 *'
     - cron: '* 0,1,2 11 4 *'
     - cron: '* 16,17,18,19 12 4 *'
     - cron: '* 22,23 13 4 *'
     - cron: '* 0,1 14 4 *'
     - cron: '* 0,1,2,3 16 4 *'
     - cron: '* 23 17 4 *'
     - cron: '* 0,1,2 18 4 *'

  workflow_dispatch: # Allows manual execution

permissions:
  contents: write

jobs:
  check-goals:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests tweepy

      - name: Run Goal Checker Script
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_COMMIT_TOKEN_2 }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_KEY_SECRET: ${{ secrets.X_API_KEY_SECRET }}
          X_API_ACCESS_TOKEN: ${{ secrets.X_API_ACCESS_TOKEN }}
          X_API_ACCESS_TOKEN_SECRET: ${{ secrets.X_API_ACCESS_TOKEN_SECRET }}
          X_API_BEARER_TOKEN: ${{ secrets.X_API_BEARER_TOKEN }}
        run: python check_for_goals.py

      - name: Commit State File
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add goal_state.json
          git commit -m "Update goal state" || echo "No changes to commit"
          git push
